import { useMemo } from 'react'

import {
  Activity,
  AppWindow,
  Database,
  Laptop,
  Mail,
  Moon,
  ScrollText,
  Settings,
  ShieldPlus,
  Sun,
  Trash2,
  UserPlus,
  Zap,
} from 'lucide-react'

import { useActiveRealm } from '@/entities/realm/model/useActiveRealm'
import { sidebarData } from '@/widgets/Sidebar/config/sidebar-data'

import type { OmniStaticItem } from './omniTypes'

export function useOmniStaticItems() {
  const realm = useActiveRealm()

  return useMemo<OmniStaticItem[]>(() => {
    const items: OmniStaticItem[] = []

    const navItems = sidebarData.navMain
      .filter((item) => !item.items)
      .map((item) => ({
        id: `nav.${item.title.toLowerCase()}`,
        label: item.title,
        group: 'Navigation' as const,
        kind: 'link' as const,
        icon: item.icon,
        href: `/${realm}${item.url === '/' ? '' : item.url}`,
        keywords: ['navigate', item.title.toLowerCase()],
      }))

    items.push(...navItems)

    items.push(
      {
        id: 'action.create-user',
        label: 'Create User',
        group: 'Suggested Actions',
        kind: 'link',
        icon: UserPlus,
        href: `/${realm}/users/new`,
        suggested: true,
      },
      {
        id: 'action.create-webhook',
        label: 'Create Webhook Endpoint',
        group: 'Suggested Actions',
        kind: 'link',
        icon: Zap,
        href: `/${realm}/events?tab=webhooks`,
        hash: 'create-webhook',
        suggested: true,
        keywords: ['webhook', 'event', 'routing', 'endpoint'],
      },
      {
        id: 'action.create-client',
        label: 'Create Client',
        group: 'Suggested Actions',
        kind: 'link',
        icon: AppWindow,
        href: `/${realm}/clients/new`,
        suggested: true,
      },
      {
        id: 'action.create-role',
        label: 'Create Role',
        group: 'Suggested Actions',
        kind: 'link',
        icon: ShieldPlus,
        href: `/${realm}/roles/new`,
        suggested: true,
      },
      {
        id: 'action.theme-light',
        label: 'Theme: Light',
        group: 'Suggested Actions',
        kind: 'action',
        icon: Sun,
        actionId: 'theme.light',
        suggested: true,
      },
      {
        id: 'action.theme-dark',
        label: 'Theme: Dark',
        group: 'Suggested Actions',
        kind: 'action',
        icon: Moon,
        actionId: 'theme.dark',
        suggested: true,
      },
      {
        id: 'action.theme-system',
        label: 'Theme: System',
        group: 'Suggested Actions',
        kind: 'action',
        icon: Laptop,
        actionId: 'theme.system',
        suggested: true,
      },
    )

    items.push(
      {
        id: 'setting.realm-name',
        label: 'Realm Name',
        description: 'Rename the realm and update its URL',
        group: 'Settings',
        kind: 'setting',
        icon: Settings,
        href: `/${realm}/settings/general`,
        hash: 'realm-name',
        keywords: ['general', 'name', 'realm'],
      },
      {
        id: 'setting.registration-enabled',
        label: 'Enable User Registration',
        description: 'Toggle the registration flow for this realm',
        group: 'Settings',
        kind: 'toggle',
        icon: UserPlus,
        href: `/${realm}/settings/general`,
        hash: 'realm-registration',
        toggleId: 'registration',
        keywords: ['registration', 'signup', 'users'],
      },
      {
        id: 'setting.email-delivery',
        label: 'Email Delivery',
        description: 'Configure SMTP for recovery and verification emails',
        group: 'Settings',
        kind: 'setting',
        icon: Mail,
        href: `/${realm}/settings/email`,
        hash: 'email-enabled',
        keywords: ['email', 'smtp', 'recovery', 'notifications'],
      },
      {
        id: 'setting.security-headers',
        label: 'Security Defenses',
        description: 'Configure security headers for auth and OIDC responses',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/security`,
        hash: 'security-x-frame-options',
        keywords: ['security', 'headers', 'csp', 'x-frame-options'],
      },
      {
        id: 'setting.security-x-frame-options',
        label: 'X-Frame-Options',
        description: 'Control frame embedding policy',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/security`,
        hash: 'security-x-frame-options',
        keywords: ['security', 'headers', 'frame', 'x-frame-options'],
      },
      {
        id: 'setting.security-content-security-policy',
        label: 'Content-Security-Policy',
        description: 'Restrict framing and content sources',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/security`,
        hash: 'security-content-security-policy',
        keywords: ['security', 'headers', 'csp', 'content security policy'],
      },
      {
        id: 'setting.security-x-content-type-options',
        label: 'X-Content-Type-Options',
        description: 'Disable MIME sniffing',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/security`,
        hash: 'security-x-content-type-options',
        keywords: ['security', 'headers', 'nosniff'],
      },
      {
        id: 'setting.security-referrer-policy',
        label: 'Referrer-Policy',
        description: 'Control referrer behavior',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/security`,
        hash: 'security-referrer-policy',
        keywords: ['security', 'headers', 'referrer'],
      },
      {
        id: 'setting.security-hsts',
        label: 'Strict-Transport-Security',
        description: 'HSTS policy for HTTPS',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/security`,
        hash: 'security-strict-transport-security',
        keywords: ['security', 'headers', 'hsts', 'strict-transport-security'],
      },
      {
        id: 'setting.email-smtp-host',
        label: 'SMTP Host',
        description: 'Configure SMTP host and credentials',
        group: 'Settings',
        kind: 'setting',
        icon: Mail,
        href: `/${realm}/settings/email`,
        hash: 'email-smtp-host',
        keywords: ['smtp', 'email', 'host'],
      },
      {
        id: 'setting.email-from-address',
        label: 'From Address',
        description: 'Sender address for outbound email',
        group: 'Settings',
        kind: 'setting',
        icon: Mail,
        href: `/${realm}/settings/email`,
        hash: 'email-from-address',
        keywords: ['email', 'from', 'sender'],
      },
      {
        id: 'setting.email-from-name',
        label: 'From Name',
        description: 'Sender display name',
        group: 'Settings',
        kind: 'setting',
        icon: Mail,
        href: `/${realm}/settings/email`,
        hash: 'email-from-name',
        keywords: ['email', 'from', 'name'],
      },
      {
        id: 'setting.email-reply-to',
        label: 'Reply-To Address',
        description: 'Reply-to override for outbound email',
        group: 'Settings',
        kind: 'setting',
        icon: Mail,
        href: `/${realm}/settings/email`,
        hash: 'email-reply-to',
        keywords: ['email', 'reply-to'],
      },
      {
        id: 'setting.email-smtp-port',
        label: 'SMTP Port',
        description: 'SMTP port for delivery',
        group: 'Settings',
        kind: 'setting',
        icon: Mail,
        href: `/${realm}/settings/email`,
        hash: 'email-smtp-port',
        keywords: ['smtp', 'port'],
      },
      {
        id: 'setting.email-smtp-security',
        label: 'SMTP Security',
        description: 'STARTTLS, TLS, or none',
        group: 'Settings',
        kind: 'setting',
        icon: Mail,
        href: `/${realm}/settings/email`,
        hash: 'email-smtp-security',
        keywords: ['smtp', 'tls', 'starttls'],
      },
      {
        id: 'setting.email-smtp-username',
        label: 'SMTP Username',
        description: 'SMTP authentication username',
        group: 'Settings',
        kind: 'setting',
        icon: Mail,
        href: `/${realm}/settings/email`,
        hash: 'email-smtp-username',
        keywords: ['smtp', 'username'],
      },
      {
        id: 'setting.email-smtp-password',
        label: 'SMTP Password',
        description: 'SMTP authentication password',
        group: 'Settings',
        kind: 'setting',
        icon: Mail,
        href: `/${realm}/settings/email`,
        hash: 'email-smtp-password',
        keywords: ['smtp', 'password'],
      },
      {
        id: 'setting.recovery-settings',
        label: 'Recovery Settings',
        description: 'Token TTL, rate limits, and reset behavior',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/recovery`,
        hash: 'recovery-revoke-sessions',
        keywords: ['recovery', 'reset', 'token', 'rate limit'],
      },
      {
        id: 'setting.recovery-token-ttl',
        label: 'Recovery Token TTL',
        description: 'Token lifetime in minutes',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/recovery`,
        hash: 'recovery-token-ttl',
        keywords: ['recovery', 'token', 'ttl'],
      },
      {
        id: 'setting.recovery-rate-limit-max',
        label: 'Recovery Rate Limit Max',
        description: 'Requests per window',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/recovery`,
        hash: 'recovery-rate-limit-max',
        keywords: ['recovery', 'rate limit', 'throttle'],
      },
      {
        id: 'setting.recovery-rate-limit-window',
        label: 'Recovery Rate Limit Window',
        description: 'Window length in minutes',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/recovery`,
        hash: 'recovery-rate-limit-window',
        keywords: ['recovery', 'rate limit', 'window'],
      },
      {
        id: 'setting.recovery-email-subject',
        label: 'Recovery Email Subject',
        description: 'Customize email subject',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/recovery`,
        hash: 'recovery-email-subject',
        keywords: ['recovery', 'email', 'subject'],
      },
      {
        id: 'setting.recovery-email-body',
        label: 'Recovery Email Body',
        description: 'Customize email body template',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/recovery`,
        hash: 'recovery-email-body',
        keywords: ['recovery', 'email', 'template'],
      },
      {
        id: 'setting.access-token-ttl',
        label: 'Access Token Lifespan',
        description: 'Access token TTL in seconds',
        group: 'Settings',
        kind: 'setting',
        icon: Zap,
        href: `/${realm}/settings/token`,
        hash: 'token-access-ttl',
        keywords: ['token', 'access', 'ttl'],
      },
      {
        id: 'setting.refresh-token-ttl',
        label: 'SSO Session Idle',
        description: 'Refresh token idle timeout in seconds',
        group: 'Settings',
        kind: 'setting',
        icon: Zap,
        href: `/${realm}/settings/token`,
        hash: 'token-refresh-ttl',
        keywords: ['token', 'refresh', 'sso'],
      },
      {
        id: 'setting.pkce-required',
        label: 'Require PKCE for Public Clients',
        description: 'Enforce PKCE for SPAs and mobile apps without secrets',
        group: 'Settings',
        kind: 'toggle',
        icon: ShieldPlus,
        href: `/${realm}/settings/token`,
        hash: 'token-pkce-required',
        toggleId: 'pkce-required',
        keywords: ['pkce', 'oidc', 'security', 'public clients'],
      },
      {
        id: 'setting.lockout-threshold',
        label: 'Lockout Threshold',
        description: 'Failed attempts before account lockout',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/token`,
        hash: 'token-lockout-threshold',
        keywords: ['lockout', 'brute force', 'security'],
      },
      {
        id: 'setting.lockout-duration',
        label: 'Lockout Duration',
        description: 'Lockout length in seconds after failed attempts',
        group: 'Settings',
        kind: 'setting',
        icon: ShieldPlus,
        href: `/${realm}/settings/token`,
        hash: 'token-lockout-duration',
        keywords: ['lockout', 'duration', 'security'],
      },
      {
        id: 'setting.observability-cleanup',
        label: 'Telemetry Settings',
        description: 'Configure log collection and cleanup actions',
        group: 'Settings',
        kind: 'setting',
        icon: Settings,
        href: `/${realm}/settings/observability`,
        hash: 'telemetry-settings',
        keywords: ['observability', 'telemetry', 'logs', 'cleanup'],
      },
      {
        id: 'setting.include-spans',
        label: 'Include Trace Spans in Logs',
        description: 'Show span entries alongside log records',
        group: 'Settings',
        kind: 'toggle',
        icon: Settings,
        href: `/${realm}/settings/observability`,
        hash: 'telemetry-include-spans',
        toggleId: 'include-spans',
        keywords: ['observability', 'logs', 'spans', 'telemetry'],
      },
      {
        id: 'setting.trace-cleanup',
        label: 'Trace Cleanup',
        description: 'Manage trace cleanup actions',
        group: 'Settings',
        kind: 'setting',
        icon: Settings,
        href: `/${realm}/settings/observability`,
        hash: 'trace-settings',
        keywords: ['observability', 'traces', 'cleanup'],
      },
    )

    items.push(
      {
        id: 'observability.logs',
        label: 'Log Explorer',
        description: 'Inspect audit logs and events',
        group: 'Observability',
        kind: 'link',
        icon: ScrollText,
        href: `/${realm}/logs?tab=logs`,
        keywords: ['observability', 'logs', 'events', 'audit'],
      },
      {
        id: 'observability.traces',
        label: 'Traces Explorer',
        description: 'Drill into request traces',
        group: 'Observability',
        kind: 'link',
        icon: Activity,
        href: `/${realm}/logs?tab=traces`,
        keywords: ['observability', 'traces', 'latency'],
      },
      {
        id: 'observability.cache',
        label: 'Cache Manager',
        description: 'View cache metrics and namespaces',
        group: 'Observability',
        kind: 'link',
        icon: Database,
        href: `/${realm}/cache`,
        keywords: ['observability', 'cache', 'flush'],
      },
      {
        id: 'danger.clear-logs',
        label: 'Clear All Logs',
        description: 'Remove stored log entries',
        group: 'Danger Zone',
        kind: 'action',
        icon: Trash2,
        actionId: 'observability.clear-logs',
        href: `/${realm}/settings/observability`,
        hash: 'logs-cleanup',
        keywords: ['danger', 'logs', 'clear'],
      },
      {
        id: 'danger.clear-traces',
        label: 'Clear All Traces',
        description: 'Remove stored traces',
        group: 'Danger Zone',
        kind: 'action',
        icon: Trash2,
        actionId: 'observability.clear-traces',
        href: `/${realm}/settings/observability`,
        hash: 'traces-cleanup',
        keywords: ['danger', 'traces', 'clear'],
      },
      {
        id: 'danger.flush-cache',
        label: 'Flush Cache',
        description: 'Purge all cache namespaces',
        group: 'Danger Zone',
        kind: 'action',
        icon: Database,
        actionId: 'observability.flush-cache',
        href: `/${realm}/cache`,
        hash: 'cache-danger-zone',
        keywords: ['danger', 'cache', 'flush'],
      },
    )

    return items
  }, [realm])
}
