//! Houses the auto-generated gRPC client and server code from the .proto file.

pub mod plugin {
    pub mod v1 {
        // This macro includes the code generated by `tonic-build` from `plugin.v1.proto`.
        tonic::include_proto!("plugin.v1");
    }
}
